create database customer_analysis;
use customer_analysis;
SHOW TABLES;
select * from shopping_data limit 20;


rename table shopping_data to data;
select * from data;

-- Ques1) What is the total revenue generated by male vs female customers?
select Gender,round(sum(purchase_amount),0)as total_revenue from data
group by Gender;


-- Ques2) Which is the top 5 product with the highest average review rating?
select Category,`Review Rating` as top_products_rating from data
order by Category desc limit 5;


-- Ques3) Which customers used a discount but still spent more than average purchase amount?
select `Customer ID`,`purchase_amount`,`Discount Applied` from data
where `Discount Applied` = 'Yes' and `purchase_amount` >(select avg(`purchase_amount`) from data); 


-- Ques4) Compare the average purchase amount between standard and express shipping.
select `Shipping Type`,round(avg(`purchase_amount`),0) as avg_purchase from data
where `Shipping Type` in ('Standard','Express')
group by  `Shipping Type` ;


-- Ques5) Do subcribed customers spend more? compare average spend and total reveneu between subscribers and non subcribers.
select 
`Subscription Status`,
count(*) as total_customer,
round(sum(purchase_amount),0) as total_amount,
round(avg(purchase_amount),0) as average_amount from data
group by `Subscription Status`
order by `Subscription Status` desc;


-- Ques6) which 5 Category have the highest percentage of purchase with discount applied?
SELECT 
    Category,
    ROUND(SUM(CASE
                WHEN `Discount Applied` = 'Yes' THEN 1
                ELSE 0
            END) * 100.0 / COUNT(*),
            0) AS discount_percentage
FROM
    data
GROUP BY Category
ORDER BY discount_percentage DESC
LIMIT 5;


-- Ques7) Segment customers into new,returning,and loyal bases on their total number of prevoius purchases,and show the count of each segment.
select 
case
when `Previous Purchases` = 0 Then "New"
when `Previous Purchases` between 1 and 5 then 'Returung'
else "Loyal"
end as customer_segment,
count(*) as cusotmer_count
from data
group by customer_segment;

-- Ques8) What are the top 3 most purchased product within each category?
WITH product_rank AS (
    SELECT 
        Category,
        `Item Purchased`,
        COUNT(*) AS total_purchases,

        ROW_NUMBER() OVER(
            PARTITION BY Category
            ORDER BY COUNT(*) DESC
        ) AS rn

    FROM data
    GROUP BY Category, `Item purchased`
)

SELECT 
    Category,
    `Item Purchased`
    total_purchases
FROM product_rank
WHERE rn <= 3;

select * from data;


-- Ques10) Whats is the revenue contribution of each age group?

select age_group,
round(sum(purchase_amount),0) as total_revenue
from data
group by age_group
order by total_revenue desc























